export type CONTEXT_TYPES =
  | "SET_OLD_DATA"
  | "SET_USER"
  | "REMOVE_USER"
  | "CHECK"
  | "UNCHECK"
  | "THEME"
  | "SELL_PRINT_DATA"
  | "SELL_REPORT_PRINT_DATA";

export const CONTEXT_TYPEs: { [key in CONTEXT_TYPES]: key } = {
  SET_OLD_DATA: "SET_OLD_DATA",
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  CHECK: "CHECK",
  UNCHECK: "UNCHECK",
  THEME: "THEME",
  SELL_PRINT_DATA: "SELL_PRINT_DATA",
  SELL_REPORT_PRINT_DATA: "SELL_REPORT_PRINT_DATA",
};
