export type CONTEXT_TYPES =
  | "SET_OLD_DATA"
  | "SET_USER"
  | "REMOVE_USER"
  | "CHECK"
  | "UNCHECK"
  | "THEME"
  | "SELL_PRINT_DATA"
  | "SELL_REPORT_PRINT_DATA"
  | "ITEM_REPORT_PRINT_DATA"
  | "KOGA_ALL_REPORT_DATA"
  | "KOGA_NULL_REPORT_DATA"
  | "KOGA_LESS_REPORT_DATA"
  | "KOGA_MOVEMENT_REPORT_DATA"
  | "BILL_PROFIT_REPORT_DATA"
  | "ITEM_PROFIT_REPORT_DATA"
  | "EXPENSE_REPORT_DATA"
  | "CASE_REPORT_DATA"
  | "RESERVATION_REPORT_DATA";

export const CONTEXT_TYPEs: { [key in CONTEXT_TYPES]: key } = {
  SET_OLD_DATA: "SET_OLD_DATA",
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  CHECK: "CHECK",
  UNCHECK: "UNCHECK",
  THEME: "THEME",
  SELL_PRINT_DATA: "SELL_PRINT_DATA",
  SELL_REPORT_PRINT_DATA: "SELL_REPORT_PRINT_DATA",

  ITEM_REPORT_PRINT_DATA: "ITEM_REPORT_PRINT_DATA",
  KOGA_ALL_REPORT_DATA: "KOGA_ALL_REPORT_DATA",
  KOGA_NULL_REPORT_DATA: "KOGA_NULL_REPORT_DATA",
  KOGA_LESS_REPORT_DATA: "KOGA_LESS_REPORT_DATA",
  KOGA_MOVEMENT_REPORT_DATA: "KOGA_MOVEMENT_REPORT_DATA",
  BILL_PROFIT_REPORT_DATA: "BILL_PROFIT_REPORT_DATA",
  ITEM_PROFIT_REPORT_DATA: "ITEM_PROFIT_REPORT_DATA",
  EXPENSE_REPORT_DATA: "EXPENSE_REPORT_DATA",
  CASE_REPORT_DATA: "CASE_REPORT_DATA",
  RESERVATION_REPORT_DATA: "RESERVATION_REPORT_DATA",
};
