export type QUERY_KEYS =
  | "CASE_MONEY"
  | "CASE_HISTORY"
  | "CASE_CHART"
  | "REPORT_MONEY_DATA"
  | "REPORT_MOST_ITEM"
  | "REPORT_MOST_ORDER"
  | "SPENDS"
  | "USERS"
  | "CLIENTS"
  | "ROLES"
  | "CAR_TYPES"
  | "CAR_MODELS"
  | "COLORS"
  | "SERVICES"
  | "EXPENSE_TYPES"
  | "PARTS"
  | "ITEMS"
  | "AUTH"
  | "ITEMS_IN_ADD"
  | "ITEM_BY_ID"
  | "EMPLOYEES_COMBOBOX"
  | "ROLE_PARTS"
  | "CHECK_SETTING"
  | "CONFIGS"
  | "LESS_ITEMS"
  | "SEARCH_USERS"
  | "SEARCH_ITEMS";

export const QUERY_KEYs: { [key in QUERY_KEYS]: key } = {
  CASE_MONEY: "CASE_MONEY",
  CASE_HISTORY: "CASE_HISTORY",
  CASE_CHART: "CASE_CHART",
  SEARCH_USERS: "SEARCH_USERS",

  REPORT_MONEY_DATA: "REPORT_MONEY_DATA",
  REPORT_MOST_ITEM: "REPORT_MOST_ITEM",
  REPORT_MOST_ORDER: "REPORT_MOST_ORDER",
  SPENDS: "SPENDS",
  USERS: "USERS",
  CLIENTS: "CLIENTS",

  ROLES: "ROLES",

  CAR_MODELS: "CAR_MODELS",
  CAR_TYPES: "CAR_TYPES",
  COLORS: "COLORS",
  SERVICES: "SERVICES",
  EXPENSE_TYPES: "EXPENSE_TYPES",

  PARTS: "PARTS",
  ITEMS: "ITEMS",
  AUTH: "AUTH",
  ITEMS_IN_ADD: "ITEMS_IN_ADD",
  ITEM_BY_ID: "ITEM_BY_ID",
  EMPLOYEES_COMBOBOX: "EMPLOYEES_COMBOBOX",
  ROLE_PARTS: "ROLE_PARTS",
  CHECK_SETTING: "CHECK_SETTING",
  CONFIGS: "CONFIGS",
  LESS_ITEMS: "LESS_ITEMS",
  SEARCH_ITEMS: "SEARCH_ITEMS",
};
