export type QUERY_KEYS =
  // USERS
  | "SEARCH_USERS"
  | "USERS"
  | "DELETED_USERS"
  | "SEARCH_DELETED_USERS"
  //CUSTOMER
  | "CUSTOMERS"
  | "DELETED_CUSTOMERS"
  | "SEARCH_DELETED_CUSTOMERS"
  | "SEARCH_CUSTOMERS"
  //EXPENSE
  | "EXPENSES"
  | "DELETED_EXPENSES"

  //EXPENSE_TYPES
  | "EXPENSE_TYPES"
  | "EXPENSE_TYPES_SELECTION"
  | "DELETED_EXPENSE_TYPES"
  | "SEARCH_DELETED_EXPENSE_TYPES"
  | "SEARCH_EXPENSE_TYPES"
  //ROLES
  | "ROLES"
  | "ROLES_SELECTION"
  | "DELETED_ROLES"
  | "SEARCH_DELETED_ROLES"
  | "SEARCH_ROLES"

  //COLORS
  | "COLORS"
  | "DELETED_COLORS"
  | "SEARCH_DELETED_COLORS"
  | "SEARCH_COLORS"
  //CAR_TYPES
  | "CAR_TYPES"
  | "DELETED_CAR_TYPES"
  | "SEARCH_DELETED_CAR_TYPES"
  | "SEARCH_CAR_TYPES"
  //CAR_MODELS
  | "CAR_MODELS"
  | "DELETED_CAR_MODELS"
  | "SEARCH_DELETED_CAR_MODELS"
  | "SEARCH_CAR_MODELS"

  //ITEM_TYPES
  | "ITEM_TYPES"
  | "ITEM_TYPES_SELECTION"
  | "DELETED_ITEM_TYPES"
  | "SEARCH_DELETED_ITEM_TYPES"
  | "SEARCH_ITEM_TYPES"
  //SERVICES
  | "SERVICES"
  | "DELETED_SERVICES"
  | "SEARCH_DELETED_SERVICES"
  | "SEARCH_SERVICES"
  //ITEMS
  | "ITEMS"
  | "SEARCH_ITEMS"
  | "DELETED_ITEMS"
  | "SEARCH_DELETED_ITEMS"
  // SELL
  | "SELL"
  | "SELL_ITEMS"
  | "DELETED_SELL_ITEMS"
  | "SELL_PRINT"
  | "SEARCH_SELLS"
  | "SELLS"
  | "DELETED_SELLS"
  | "SEARCH_DELETED_SELLS"
  | "SELF_DELETED_SELL_ITEMS"
  | "SEARCH_SELF_DELETED_SELL_ITEMS"
  //
  | "CASE_MONEY"
  | "CASE_HISTORY"
  | "CASE_CHART"
  | "REPORT_MONEY_DATA"
  | "REPORT_MOST_ITEM"
  | "REPORT_MOST_ORDER"
  | "PARTS"
  | "AUTH"
  | "ITEM_BY_ID"
  | "ROLE_PARTS"
  | "CHECK_SETTING"
  | "CONFIGS";

export const QUERY_KEYs: { [key in QUERY_KEYS]: key } = {
  //USER
  USERS: "USERS",
  SEARCH_USERS: "SEARCH_USERS",
  DELETED_USERS: "DELETED_USERS",
  SEARCH_DELETED_USERS: "SEARCH_DELETED_USERS",
  //CUSTOMER
  CUSTOMERS: "CUSTOMERS",
  SEARCH_CUSTOMERS: "SEARCH_CUSTOMERS",
  SEARCH_DELETED_CUSTOMERS: "SEARCH_DELETED_CUSTOMERS",
  DELETED_CUSTOMERS: "DELETED_CUSTOMERS",
  //ROLE
  ROLES: "ROLES",
  ROLES_SELECTION: "ROLES_SELECTION",
  SEARCH_ROLES: "SEARCH_ROLES",
  SEARCH_DELETED_ROLES: "SEARCH_DELETED_ROLES",
  DELETED_ROLES: "DELETED_ROLES",
  //COLOR
  COLORS: "COLORS",
  SEARCH_COLORS: "SEARCH_COLORS",
  SEARCH_DELETED_COLORS: "SEARCH_DELETED_COLORS",
  DELETED_COLORS: "DELETED_COLORS",
  //CAR_MODEL
  CAR_MODELS: "CAR_MODELS",
  SEARCH_CAR_MODELS: "SEARCH_CAR_MODELS",
  SEARCH_DELETED_CAR_MODELS: "SEARCH_DELETED_CAR_MODELS",
  DELETED_CAR_MODELS: "DELETED_CAR_MODELS",
  //CAR_TYPE
  CAR_TYPES: "CAR_TYPES",
  SEARCH_CAR_TYPES: "SEARCH_CAR_TYPES",
  SEARCH_DELETED_CAR_TYPES: "SEARCH_DELETED_CAR_TYPES",
  DELETED_CAR_TYPES: "DELETED_CAR_TYPES",
  //ITEM_TYPE
  ITEM_TYPES: "ITEM_TYPES",
  ITEM_TYPES_SELECTION: "ITEM_TYPES_SELECTION",

  SEARCH_ITEM_TYPES: "SEARCH_ITEM_TYPES",
  SEARCH_DELETED_ITEM_TYPES: "SEARCH_DELETED_ITEM_TYPES",
  DELETED_ITEM_TYPES: "DELETED_ITEM_TYPES",
  //SERVICE
  SERVICES: "SERVICES",
  SEARCH_SERVICES: "SEARCH_SERVICES",
  SEARCH_DELETED_SERVICES: "SEARCH_DELETED_SERVICES",
  DELETED_SERVICES: "DELETED_SERVICES",
  //EXPENSE_TYPE
  EXPENSE_TYPES_SELECTION: "EXPENSE_TYPES_SELECTION",
  EXPENSE_TYPES: "EXPENSE_TYPES",
  SEARCH_EXPENSE_TYPES: "SEARCH_EXPENSE_TYPES",
  SEARCH_DELETED_EXPENSE_TYPES: "SEARCH_DELETED_EXPENSE_TYPES",
  DELETED_EXPENSE_TYPES: "DELETED_EXPENSE_TYPES",
  //EXPENSE
  EXPENSES: "EXPENSES",
  DELETED_EXPENSES: "DELETED_EXPENSES",
  CASE_MONEY: "CASE_MONEY",
  CASE_HISTORY: "CASE_HISTORY",
  CASE_CHART: "CASE_CHART",

  //ITEMS
  ITEMS: "ITEMS",
  SEARCH_ITEMS: "SEARCH_ITEMS",
  DELETED_ITEMS: "DELETED_ITEMS",
  SEARCH_DELETED_ITEMS: "SEARCH_DELETED_ITEMS",
  //SELL
  SELL: "SELL",
  SELL_ITEMS: "SELL_ITEMS",
  DELETED_SELL_ITEMS: "DELETED_SELL_ITEMS",

  SELL_PRINT: "SELL_PRINT",
  SELLS: "SELLS",
  SEARCH_SELLS: "SEARCH_SELLS",
  DELETED_SELLS: "DELETED_SELLS",
  SEARCH_DELETED_SELLS: "SEARCH_DELETED_SELLS",

  SELF_DELETED_SELL_ITEMS: "SELF_DELETED_SELL_ITEMS",
  SEARCH_SELF_DELETED_SELL_ITEMS: "SEARCH_SELF_DELETED_SELL_ITEMS",

  //
  REPORT_MONEY_DATA: "REPORT_MONEY_DATA",
  REPORT_MOST_ITEM: "REPORT_MOST_ITEM",
  REPORT_MOST_ORDER: "REPORT_MOST_ORDER",

  PARTS: "PARTS",
  AUTH: "AUTH",
  ITEM_BY_ID: "ITEM_BY_ID",
  ROLE_PARTS: "ROLE_PARTS",
  CHECK_SETTING: "CHECK_SETTING",
  CONFIGS: "CONFIGS",
};
